DROP PROCEDURE IF EXISTS `aasv_travelmode_getall`;

DELIMITER $$

/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ $$
CREATE  PROCEDURE `aasv_travelmode_getall`()
BEGIN
      SELECT TMODE,TYPE,NOFPASSENGER FROM aasv_travelmode;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;

--
-- Definition of procedure `aasv_travelplan_insert`
--

DROP PROCEDURE IF EXISTS `aasv_travelplan_insert`;

DELIMITER $$

/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ $$
CREATE  PROCEDURE `aasv_travelplan_insert`(
USERID INT,
CURRLOCATION VARCHAR(30),
STARTLOCATION VARCHAR(30),
ENDLOCATION VARCHAR(30),
TRAVELTIME VARCHAR(15),
TRAVELMODE VARCHAR(15),
NOOFPASSENGER TINYINT)
BEGIN
     INSERT INTO aasv_travel(USERID,CURRLOCATION,STARTLOCATION,ENDLOCATION,TRAVELTIME,TRAVELMODE,NOOFPASSENGER,DATCRETRAVEL)
       VALUES(USERID,CURRLOCATION,STARTLOCATION,ENDLOCATION,TRAVELTIME,TRAVELMODE,NOOFPASSENGER,NOW());
     SELECT @ROWCOUNT;       
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;

--
-- Definition of procedure `aasv_user_getloginuserdata`
--

DROP PROCEDURE IF EXISTS `aasv_user_getloginuserdata`;

DELIMITER $$

/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ $$
CREATE  PROCEDURE `aasv_user_getloginuserdata`(
/*LOGIN VARCHAR(15),USERPASSWORD VARCHAR(15)*/
MOBILENO VARCHAR(11)
)
BEGIN
    /*SELECT USERID,UFNAME,ULNAME,GENDER,AGE,UCONTACTNO FROM aasv_user WHERE  ULOGIN=LOGIN  AND UPASSWORD=USERPASSWORD;*/
    SELECT USERID,UFNAME,ULNAME,GENDER,AGE,UCONTACTNO FROM aasv_user WHERE  UCONTACTNO=MOBILENO;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;

--
-- Definition of procedure `aasv_user_getusercitylocalites`
--

DROP PROCEDURE IF EXISTS `aasv_user_getusercitylocalites`;

DELIMITER $$

/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ $$
CREATE  PROCEDURE `aasv_user_getusercitylocalites`(LOGINUSERID INT)
BEGIN
      SELECT LOCALITYID,LOCALITY FROM aasv_citylocalities a;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;

--
-- Definition of procedure `aasv_user_insert`
--

DROP PROCEDURE IF EXISTS `aasv_user_insert`;

DELIMITER $$

/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ $$
CREATE  PROCEDURE `aasv_user_insert`(FNAME VARCHAR(20),
LNAME VARCHAR(20),
SEX SMALLINT,
AGE SMALLINT,
MOBILENO VARCHAR(11))
BEGIN

      INSERT INTO aasv_user(UFNAME,ULNAME,GENDER,AGE,UCONTACTNO,DATCREUSER)
       VALUES(FNAME,LNAME,SEX,AGE,MOBILENO,NOW());

       CALL aasv_user_getloginuserdata(MOBILENO);
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;

--
-- Definition of procedure `aasv_user_travelconfirm`
--

DROP PROCEDURE IF EXISTS `aasv_user_travelconfirm`;

DELIMITER $$

/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ $$
CREATE  PROCEDURE `aasv_user_travelconfirm`(
CURUSERTRAVELID INT,USERTRAVELID INT)
BEGIN
      INSERT INTO aasv_travelconfirmdet(TRAVELID,MAPEDTRAVELID,CONFIRMEDDAT,ARCHIVE,ARCHIVEDATE)
      VALUES(CURUSERTRAVELID,USERTRAVELID,NOW(),0,NULL);
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;

--
-- Definition of procedure `aasv_user_traveldelete`
--

DROP PROCEDURE IF EXISTS `aasv_user_traveldelete`;

DELIMITER $$

/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ $$
CREATE  PROCEDURE `aasv_user_traveldelete`(SELTRAVELID INT)
BEGIN
      DELETE FROM aasv_travel WHERE TRAVELID=SELTRAVELID ;
      UPDATE aasv_travelconfirmdet SET ARCHIVE=1 , ARCHIVEDATE=NOW() WHERE  TRAVELID=SELTRAVELID;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;

--
-- Definition of procedure `aasv_user_travelmatch`
--

DROP PROCEDURE IF EXISTS `aasv_user_travelmatch`;

DELIMITER $$

/*!50003 SET @TEMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION' */ $$
CREATE  PROCEDURE `aasv_user_travelmatch`(LOGINUSERID INT)
BEGIN
      SELECT otherusers.TRAVELID,matchusers.USERID,matchusers.UCONTACTNO,otherusers.TRAVELID,matchusers.UFNAME ,matchusers.ULNAME,matchusers.GENDER,matchusers.AGE,matchusers.UCONTACTNO,
        otherusers.CURRLOCATION,otherusers.STARTLOCATION,otherusers.ENDLOCATION,otherusers.STARTLOCATION,otherusers.NOOFPASSENGER,otherusers.TRAVELMODE,otherusers.TRAVELTIME,
      otherusers.USERID=LOGINUSERID AS ISSELFPLAN,(SELECT 1 FROM aasv_travelconfirmdet confirmdet WHERE confirmdet.MAPEDTRAVELID=otherusers.TRAVELID AND ARCHIVE=0) AS ISCONFIRMED
      FROM aasv_travel otherusers
      INNER JOIN aasv_user matchusers ON matchusers.USERID=otherusers.USERID
      WHERE EXISTS(SELECT 1 FROM aasv_travel connecteduser
            WHERE connecteduser.CURRLOCATION=otherusers.CURRLOCATION AND
        connecteduser.ENDLOCATION =otherusers.ENDLOCATION AND
      connecteduser.USERID=LOGINUSERID ANd connecteduser.NOOFPASSENGER +otherusers.NOOFPASSENGER
       <= (SELECT NOFPASSENGER FROM aasv_travelmode WHERE aasv_travelmode.TYPE =otherusers.TRAVELMODE))
      ORDER BY ISSELFPLAN DESC;
END $$
/*!50003 SET SESSION SQL_MODE=@TEMP_SQL_MODE */  $$

DELIMITER ;



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;